### ISSUE TITLE
CDE-compliant BCSwiftDCBOR

### ISSUE THREAD

**Issue by cyberphone** [BlockchainCommons/BCSwiftDCBOR#4]
Just out of curiosity I patched the DCBOR implementation to make it CDE-compliant:
https://github.com/cyberphone/BCSwiftDCBOR
Since I had very limited knowledge of the code base, Swift, and Xcode it took me a day.

I wasn't able to test it with the Gordian Envelope code, but I would eat my hat if it did not work right-out-of-the-box (modulo tests that check output).
https://github.com/cyberphone/BCSwiftDCBOR/blob/master/Tests/DCBORTests/CodingTests.swift#L221

300-line JS CDE encoder:
https://gist.github.com/cyberphone/d0f7a99da6afb397955645baad578bea#file-cde-js-L317

**Comment by wolfmcnally** [comment]
DCBOR is already CDE-compliant.

**Comment by laurencelundblade** [comment]
1) If both the encoder and decoder are doing DCBOR, then all is OK
2) Same if both are doing CDE
3) If the encoder is sending CDE, a DCBOR decoder will correctly reject many things
4) If the encoder is sending DCBOR, the CDE decoder will happily accept everything  (including an enthusiastic CDE decoder that does conformance checking), but maybe the application layer will be unhappy.

You probably shouldn’t ever do 3) or 4) unless you’ve worked things out at the protocol/application layer. I don’t think you should expect that to work. DCBOR encoders will and must turn a float 2.0 into an integer 2. CDE-based protocols probably don’t want that so CDE-based protocols shouldn’t encode in DCBOR mode.

It seems like you could construct a CBOR protocol that could work for either 3) or 4) by having rules about what is expected, avoiding things like UnDef, but I don't see much purpose to do this.

It is probably wrong to say that DCBOR is "CDE compliant". More correct to say DCBOR builds on CDE. The draft doesn't actually say the DCBOR is CDE compliant. The draft seems correct in its discussion of CDE.

I looked at this to see if there were any issues with the way I've implemented DCBOR and CDE in QCBOR. Didn't find any.

**Comment by wolfmcnally** [comment]
@laurencelundblade 
> It is probably wrong to say that DCBOR is "CDE compliant". More correct to say DCBOR builds on CDE. The draft doesn't actually say the DCBOR is CDE compliant. The draft seems correct in its discussion of CDE.

By "CDE-compliant" I meant that all valid dCBOR is valid CDE. No more or less.
